### ISSUE TITLE
New SDRPlay API 1.8.1

### ISSUE THREAD

**Issue by frspin** [jazzkutya/sdrplay-wine-fakedll#3]
Now that 1.8.1 API is released for Windows and also for Linux, can we have a new version of this "fake DLL"?

Regards
Franco Spinelli
IW2DHW

**Comment by jazzkutya** [comment]
As far as I know the the API at the lowest level did not change (just some parameters for some calls) so in theory it should work without changes. I will test it soon and do necessary changes if needed.

**Comment by jazzkutya** [comment]
Tested it and found a problem with the 32bit fakedll. I released new precompiled fakedlls that fix the problem with HDSDR. SDRConsole should work with the older fakedlls tho (since it is 64bit).

**Comment by jazzkutya** [comment]
I have updated the wiki too to reflect new version numbers and stuff. Also mentioned necessary cleanup if reinstalling the 32 bit libds on 64 bit linux for hdsdr.
